### ISSUE TITLE
RFC #0398 - Tracking for RouteInfo Metadata

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#10]
## [RFC #0398](https://github.com/emberjs/rfcs/pull/0398) - Tracking for RouteInfo Metadata

Champion: @chadhietala 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [emberjs/ember.js](https://github.com/emberjs/ember.js)

- [x] https://github.com/emberjs/ember.js/pull/17256

#### [tildeio/router.js](https://github.com/tildeio/router.js)

- [x] https://github.com/tileio/router.js/pull/275

**Comment by rwjblue** [comment]
Slated for release in 3.10

**Comment by kategengler** [comment]
Released in 3.10
