### ISSUE TITLE
RFC #0226 - Tracking for Named Blocks

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#13]
## [RFC #0226](https://github.com/emberjs/rfcs/pull/0226) - Tracking for Named Blocks

Champion: @wycats 	

---

> All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

### Ember.js Team:
N/A

### Ember CLI Team:
N/A

### Ember Data Team:
N/A

### Learning Team:
N/A

### Steering Committee:
N/A

**Comment by locks** [comment]
Superseded by https://github.com/emberjs/rfcs/pull/460.

**Comment by Exelord** [comment]
Is there any tracking PR for https://github.com/emberjs/rfcs/pull/460 ?

**Comment by kategengler** [comment]
@Exelord Yes, https://github.com/emberjs/rfc-tracking/issues/44

**Comment by Exelord** [comment]
Thanks. Its missing the reference

**Comment by kategengler** [comment]
It is linked from the merged RFC
