### ISSUE TITLE
RFC #0372 - Tracking for modelFactoryFor

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#16]
## [RFC #0372](https://github.com/emberjs/rfcs/pull/0372) - Tracking for modelFactoryFor

Champion: @igorT 	

---

> All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

### Ember Data Team:

This RFC is being revisited and replaced with a new RFC
https://github.com/emberjs/rfcs/pull/372#issuecomment-462896835

**Comment by runspired** [comment]
We reverted this and are pursuing a new RFC direction.
