### ISSUE TITLE
RFC #0370 - Tracking for Deprecate `computed().volatile()`

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#17]
## [RFC #0370](https://github.com/emberjs/rfcs/pull/0370) - Tracking for Deprecate `computed().volatile()`

Champion: @rwjblue 	

---

> All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

### Ember.js Team:

- [x] Implement feature https://github.com/emberjs/ember.js/pull/17470

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

## [Deprecation Guide](https://github.com/ember-learn/deprecation-app)

- [x] Add to the deprecation guide https://github.com/ember-learn/deprecation-app/pull/254 / https://github.com/ember-learn/deprecation-app/pull/317

### Steering Committee:

N/A

**Comment by rwjblue** [comment]
Done! 🎉

**Comment by kategengler** [comment]
Released in 3.9.0
