### ISSUE TITLE
RFC #0293 - Tracking for Ember Data Record Data

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#24]
## [RFC #0293](https://github.com/emberjs/rfcs/pull/0293) - Tracking for Ember Data Record Data

Champion: @igorT 	

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

### Ember.js Team:
N/A

### Ember CLI Team:
N/A

### Ember Data Team:
- implement RecordData (https://github.com/emberjs/data/pulls?utf8=%E2%9C%93&q=is%3Apr+record+data+)

### Learning Team:

- [ ] Write API docs for it
- [ ] Create a page in cli.emberjs.com that teaches the basics

(The Learning team does not have the knowledge to write these resources or lead them, but we can help with PR reviews and brainstorming)

### Steering Committee:
N/A

**Comment by jenweber** [comment]
The Learning team is available to review any docs-related PRs. We don't know enough to lead/write them, but let us know how we can help.

**Comment by runspired** [comment]
This feature landed in 3.5, but we intentionally opted to not-document more than a little bit of it because the initial implementation was problematic. A new design is being tracked in #51, closing in favor.
