### ISSUE TITLE
RFC #0364 - Tracking for Ember 2018 Roadmap

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#28]
## [RFC #0364](https://github.com/emberjs/rfcs/blob/master/text/0364-roadmap-2018.md) - Tracking for Ember 2018 Roadmap

Champion: @tomdale 
---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

**Comment by rwjblue** [comment]
@kategengler - I'm not sure exactly how to handle this one. It's not as clear cut to me as the others. Do we just make this the overarching "octane" tracking issue?

**Comment by MelSumner** [comment]
@tomdale @rwjblue @kategengler we should figure this out so it doesn't happen to the 2019 Roadmap RFC.
