### ISSUE TITLE
RFC #0449 - Tracking for Deprecate `{{partial}}`

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#38]
## [RFC #0449](https://github.com/emberjs/rfcs/blob/master/text/0449-deprecate-partials.md) - Tracking for Deprecate `{{partial}}`

Champion: @rwjblue 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [ember.js](https://github.com/emberjs/ember.js)

- [ ] Implementation

### Ember CLI Team:

N/A

### Ember Data Team:

N/A

#### [guides-source](https://github.com/ember-learn/guides-source)

N/A

#### [deprecation-app](https://github.com/ember-learn/deprecation-app)

- [ ] Write deprecation guide

### Steering Committee:

N/A

**Comment by GavinJoyce** [comment]
I'll work on implementing this

**Comment by GavinJoyce** [comment]
These are ready for review:

 * https://github.com/emberjs/ember.js/pull/18491
 * https://github.com/ember-learn/deprecation-app/pull/456

**Comment by locks** [comment]
`{{partial}}` was deprecated as of Ember v3.15.0 and is additionally linted against.

**Comment by locks** [comment]
Thanks for the help!
