### ISSUE TITLE
RFC #0446 - Tracking for Contribution Guides

### ISSUE THREAD

**Issue by kategengler** [emberjs/rfc-tracking#39]
## [RFC #0446](https://github.com/emberjs/rfcs/blob/master/text/0446-contribution-guides.md) - Tracking for Contribution Guides

Champion: @jessica-jordan 

---

<details>
  <summary>Expand for Instructions</summary>
  
All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

See [the README](https://github.com/emberjs/rfc-tracking/blob/master/README.md) for more information
See https://github.com/emberjs/rfc-tracking/issues/3 for an example

Under each team, for each repo requiring work for the RFC under that team:
`### [repo name](repo url)`

`- [ ] (issue or pr) description, (issue or pr) link` 

Remove Repos that do not apply, conversely, there will probably be other repos that need work and should be added.
</details>

#### [guides-source](https://github.com/ember-learn/guides-source)

- [ ]  create content https://github.com/ember-learn/contribution-guides/issues/1
- [ ]  update reference from guides-source https://github.com/ember-learn/guides-source/issues/1141

### Steering Committee:

N/A

**Comment by alexeykostevich** [comment]
A related issue that has proposals on a demo environment for issue reporters:
https://github.com/emberjs/ember.js/issues/18460
