### ISSUE TITLE
RFC #0465 - Tracking for Record Data Errors

### ISSUE THREAD

**Issue by igorT** [emberjs/rfc-tracking#46]
## [RFC #0465](https://github.com/igorT/rfcs/blob/igor/record-data-errors/text/0465-record-data-errors.md) - Tracking for Record Data Errors
Champion: @igorT 

---

### Learning Team

No action needed. See [the general DataRecord tracking](https://github.com/emberjs/rfc-tracking/issues/24)

**Comment by runspired** [comment]
This is finally activated in 3.28 beta. We still need documentation though so this should be left open.
