### ISSUE TITLE
RFC #0463 - Tracking for Record Data State

### ISSUE THREAD

**Issue by igorT** [emberjs/rfc-tracking#47]
## [RFC #0463](https://github.com/emberjs/rfcs/blob/master/text/0463-record-data-state.md) - Tracking for Record Data State

Champion: @igorT 
---

#### [ember-data](https://github.com/emberjs/data)

- [ ] A thing required for this RFC in this repo, https://github.com/emberjs/data/pull/ABCDE

### Steering Committee:

N/A

**Comment by runspired** [comment]
This is finally activated in 3.28 beta. We still need documentation though so this should be left open.
