### ISSUE TITLE
RFC #0452 - Tracking for Ember Data Medium Term plan

### ISSUE THREAD

**Issue by igorT** [emberjs/rfc-tracking#50]
## [RFC #0456](https://github.com/emberjs/rfcs/blob/d1d557d29f46fca13f035023a513cd30ae599f6a/text/0000-ember-data-refactor.md) - Tracking for Ember Data Medium Term plan

Champion: @igorT 

### Learning Team:

This RFC is a roadmap-style plan, so no Learning Team work is needed for this specific RFC. Learning resource work will be described in individual feature/deprecation RFCs.

**Comment by runspired** [comment]
This RFC required no implementation, it was just merely a state-of-the-world update. Closing as no further actions to take.
